name: PHP Coding Standards

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP_CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 --ignore=vendor/*,.psalm/*,.github/* --exclude=Generic.Files.SideEffects ./

#      - name: Run PHP_CodeBeautifier
#        run: ~/.composer/vendor/bin/phpcbf --standard=PSR12 ./

      - name: Upload phpcs report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-report
          path: phpcs.xml